#!/usr/bin/env python3
"""
Train the confidence prediction model.

This model predicts per-measurement expected error given:
- Pose landmark visibility scores
- Image quality metrics
- Extractor type used

Requires ground truth data to train. See:
  POST /api/v1/validation/ground-truth  (to collect data)
  python scripts/import_ground_truth.py (to bulk import)

Usage:
  python -m app.ml.training.scripts.train_confidence_model
"""

import sys
import os
import json
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
import logging

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../../../.."))

from app.ml.confidence_predictor import ConfidenceNet, MEASUREMENT_NAMES, EXTRACTOR_QUALITY

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

CHECKPOINT_DIR = os.path.join(os.path.dirname(__file__), "..", "checkpoints")
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

OUTPUT_PATH = os.path.join(CHECKPOINT_DIR, "confidence_predictor.pt")

# Ground truth validation results file (generated by validation runner)
VALIDATION_RESULTS_PATH = os.path.join(
    os.path.dirname(__file__), "../../data/validation/validation_results.json"
)


def load_training_data():
    """
    Load training data from validation results.

    Each sample needs:
    - Input features (visibility, frame ratio, angle, extractor type)
    - Labels (per-measurement absolute error in cm)
    """
    if not os.path.exists(VALIDATION_RESULTS_PATH):
        logger.error(
            "No validation results found at %s. "
            "Run the validation pipeline first to generate training data:\n"
            "  POST /api/v1/measurements/validate",
            VALIDATION_RESULTS_PATH,
        )
        return None, None

    with open(VALIDATION_RESULTS_PATH) as f:
        results = json.load(f)

    samples = results.get("samples", [])
    if len(samples) < 20:
        logger.error(
            "Need at least 20 validation samples to train. Got %d. "
            "Collect more ground truth data first.",
            len(samples),
        )
        return None, None

    features_list = []
    labels_list = []

    extractor_types = list(EXTRACTOR_QUALITY.keys())

    for sample in samples:
        # Build feature vector (same structure as ConfidencePredictor._build_features)
        vis = np.full(33, 0.5)
        vis_scores = sample.get("visibility_scores", {})
        for i, v in enumerate(vis_scores.values()):
            if i < 33:
                vis[i] = v

        frame_ratio = sample.get("body_to_frame_ratio", 0.7)
        angle = sample.get("pose_angle_degrees", 0.0) / 90.0
        scalars = np.array([frame_ratio, angle])

        method = sample.get("extractor_method", "simple_fallback")
        one_hot = np.zeros(len(extractor_types))
        if method in extractor_types:
            one_hot[extractor_types.index(method)] = 1.0

        features = np.concatenate([vis, scalars, one_hot])
        features_list.append(features)

        # Labels: absolute error per measurement (cm)
        errors = []
        for name in MEASUREMENT_NAMES:
            predicted = sample.get(f"predicted_{name}", 0)
            actual = sample.get(f"actual_{name}", 0)
            if predicted and actual:
                errors.append(abs(predicted - actual))
            else:
                errors.append(3.0)  # default error when data missing
        labels_list.append(errors)

    X = np.array(features_list, dtype=np.float32)
    y = np.array(labels_list, dtype=np.float32)

    logger.info("Loaded %d training samples with %d features", len(X), X.shape[1])
    return X, y


def train(epochs=100, lr=0.001, batch_size=32):
    X, y = load_training_data()
    if X is None:
        logger.error("Cannot train without data. Exiting.")
        return

    # Convert errors to confidence: conf = 1 - clip(error / 10, 0, 1)
    y_conf = np.clip(1.0 - y / 10.0, 0.1, 0.98).astype(np.float32)
    y_error = y.astype(np.float32)

    # Split 80/20
    n = len(X)
    split = int(n * 0.8)
    indices = np.random.permutation(n)
    train_idx, val_idx = indices[:split], indices[split:]

    train_ds = TensorDataset(
        torch.tensor(X[train_idx]),
        torch.tensor(y_conf[train_idx]),
        torch.tensor(y_error[train_idx]),
    )
    val_ds = TensorDataset(
        torch.tensor(X[val_idx]),
        torch.tensor(y_conf[val_idx]),
        torch.tensor(y_error[val_idx]),
    )

    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_ds, batch_size=batch_size)

    model = ConfidenceNet(input_dim=X.shape[1])
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    conf_loss_fn = nn.MSELoss()
    error_loss_fn = nn.L1Loss()

    best_val_loss = float("inf")

    for epoch in range(epochs):
        model.train()
        train_loss = 0
        for x_batch, y_conf_batch, y_err_batch in train_loader:
            optimizer.zero_grad()
            pred_conf, pred_err = model(x_batch)
            loss = conf_loss_fn(pred_conf, y_conf_batch) + error_loss_fn(pred_err, y_err_batch)
            loss.backward()
            optimizer.step()
            train_loss += loss.item()

        # Validation
        model.eval()
        val_loss = 0
        with torch.no_grad():
            for x_batch, y_conf_batch, y_err_batch in val_loader:
                pred_conf, pred_err = model(x_batch)
                loss = conf_loss_fn(pred_conf, y_conf_batch) + error_loss_fn(pred_err, y_err_batch)
                val_loss += loss.item()

        avg_train = train_loss / len(train_loader)
        avg_val = val_loss / max(len(val_loader), 1)

        if (epoch + 1) % 10 == 0:
            logger.info("Epoch %d/%d  train_loss=%.4f  val_loss=%.4f", epoch + 1, epochs, avg_train, avg_val)

        if avg_val < best_val_loss:
            best_val_loss = avg_val
            torch.save(model.state_dict(), OUTPUT_PATH)

    logger.info("Training complete. Best val_loss=%.4f. Model saved to %s", best_val_loss, OUTPUT_PATH)


if __name__ == "__main__":
    train()
